sessionsaver: update code for Gedit.TabState enum value
The GeditTabState enum is now documented with GTK-Doc, and there is a
field marked with `/*< private >*/`, so it is probably for that reason
that the code needs to be adapted.

The Python error was:
```
Traceback (most recent call last):
  File "/home/seb/.imovo/i/lib64/gedit/plugins/sessionsaver/windowactivable.py", line 74, in _session_menu_action
    self.load_session(session)
  File "/home/seb/.imovo/i/lib64/gedit/plugins/sessionsaver/windowactivable.py", line 114, in load_session
    if self.needs_new_window_to_load_session():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seb/.imovo/i/lib64/gedit/plugins/sessionsaver/windowactivable.py", line 107, in needs_new_window_to_load_session
    tab.get_state() == Gedit.TabState.STATE_NORMAL):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'TabState' has no attribute 'STATE_NORMAL'
```

Fixes https://gitlab.gnome.org/GNOME/gedit-plugins/-/issues/58